#define NOMINMAX
#include "float_vertex_pipeline.hpp"
#include "float_draw_renderer.hpp"
#include "live_renderer.hpp"
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <iostream>
using Microsoft::WRL::ComPtr;
using namespace malemod::witcher;
static void Check(bool b,const char* s){if(!b)throw std::runtime_error(std::string(s)+": "+FloatDrawError());}
static void HR(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D12 output test failed HRESULT="+std::to_string(h));}
static ComPtr<ID3DBlob> Shader(const char* source,const char* target){ComPtr<ID3DBlob> b,e;auto h=D3DCompile(source,std::strlen(source),nullptr,nullptr,nullptr,"main",target,D3DCOMPILE_ENABLE_STRICTNESS,0,&b,&e);if(FAILED(h)){if(e)std::cerr<<static_cast<const char*>(e->GetBufferPointer());HR(h);}return b;}
int main(int argc,char** argv){try{
 ComPtr<IDXGIFactory4> factory;HR(CreateDXGIFactory1(IID_PPV_ARGS(&factory)));ComPtr<IDXGIAdapter> warp;if(argc==2&&!std::strcmp(argv[1],"--hardware")){ComPtr<IDXGIFactory6> latestFactory;HR(factory.As(&latestFactory));HR(latestFactory->EnumAdapterByGpuPreference(0,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&warp)));}else HR(factory->EnumWarpAdapter(IID_PPV_ARGS(&warp)));ComPtr<ID3D12Device> device;HR(D3D12CreateDevice(warp.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device)));
 D3D12_INPUT_ELEMENT_DESC original[]={
  {"POSITION",0,DXGI_FORMAT_R16G16B16A16_UNORM,0,0,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,0},
  {"BLENDINDICES",0,DXGI_FORMAT_R8G8B8A8_UINT,0,8,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,0},
  {"BLENDWEIGHT",0,DXGI_FORMAT_R8G8B8A8_UNORM,0,12,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,0},
  {"TEXCOORD",0,DXGI_FORMAT_R32G32_FLOAT,1,0,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,0},
  {"NORMAL",0,DXGI_FORMAT_R10G10B10A2_UNORM,2,0,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,0},
  {"TANGENT",0,DXGI_FORMAT_R10G10B10A2_UNORM,2,4,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,0}};
 FloatSkinLayout layout({original,6});Check(layout.Slot()==0,"Wrong float output slot");
 auto invalid=original[1];original[1].AlignedByteOffset=7;bool rejected=false;try{FloatSkinLayout bad({original,4});}catch(const std::invalid_argument&){rejected=true;}original[1]=invalid;Check(rejected,"Unknown original skin layout accepted");
 D3D12_ROOT_SIGNATURE_DESC rootDesc{};rootDesc.Flags=D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;ComPtr<ID3DBlob> rootBlob,errors;HR(D3D12SerializeRootSignature(&rootDesc,D3D_ROOT_SIGNATURE_VERSION_1,&rootBlob,&errors));ComPtr<ID3D12RootSignature> root;HR(device->CreateRootSignature(0,rootBlob->GetBufferPointer(),rootBlob->GetBufferSize(),IID_PPV_ARGS(&root)));
 auto vs=Shader(R"(
struct Input {float3 p:POSITION;uint4 bones:BLENDINDICES;float4 weights:BLENDWEIGHT;float2 uv:TEXCOORD;float3 n:NORMAL;float4 t:TANGENT;};
struct Output {float4 p:SV_Position;float4 color:COLOR;};
Output main(Input v){Output o;float3 dequantized=v.p*float3(1,1,1)+float3(0,0,0);
 o.p=float4(dequantized.x-2,dequantized.y,0,1);float sum=v.weights.x+v.weights.y+v.weights.z+v.weights.w;
 o.color=float4(v.bones.x/7.0,v.weights.x/sum,v.uv.x,v.n.z+v.t.w);return o;}
)","vs_5_0");
 auto ps=Shader("float4 main(float4 p:SV_Position,float4 color:COLOR):SV_Target{return color;}","ps_5_0");
 D3D12_GRAPHICS_PIPELINE_STATE_DESC desc{};desc.pRootSignature=root.Get();desc.VS={vs->GetBufferPointer(),vs->GetBufferSize()};desc.PS={ps->GetBufferPointer(),ps->GetBufferSize()};desc.InputLayout={original,6};desc.SampleMask=UINT_MAX;
 desc.RasterizerState.FillMode=D3D12_FILL_MODE_SOLID;desc.RasterizerState.CullMode=D3D12_CULL_MODE_NONE;desc.RasterizerState.DepthClipEnable=TRUE;
 auto& blend=desc.BlendState.RenderTarget[0];blend.SrcBlend=D3D12_BLEND_ONE;blend.DestBlend=D3D12_BLEND_ZERO;blend.BlendOp=D3D12_BLEND_OP_ADD;blend.SrcBlendAlpha=D3D12_BLEND_ONE;blend.DestBlendAlpha=D3D12_BLEND_ZERO;blend.BlendOpAlpha=D3D12_BLEND_OP_ADD;blend.LogicOp=D3D12_LOGIC_OP_NOOP;blend.RenderTargetWriteMask=D3D12_COLOR_WRITE_ENABLE_ALL;
 desc.DepthStencilState.DepthFunc=D3D12_COMPARISON_FUNC_ALWAYS;desc.DepthStencilState.FrontFace.StencilFunc=D3D12_COMPARISON_FUNC_ALWAYS;desc.DepthStencilState.FrontFace.StencilFailOp=desc.DepthStencilState.FrontFace.StencilDepthFailOp=desc.DepthStencilState.FrontFace.StencilPassOp=D3D12_STENCIL_OP_KEEP;desc.DepthStencilState.BackFace=desc.DepthStencilState.FrontFace;
 desc.PrimitiveTopologyType=D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;desc.NumRenderTargets=1;desc.RTVFormats[0]=DXGI_FORMAT_R32G32B32A32_FLOAT;desc.SampleDesc.Count=1;
 ComPtr<ID3D12PipelineState> pipeline;HR(device->CreateGraphicsPipelineState(&desc,IID_PPV_ARGS(&pipeline)));RegisterFloatDrawPipeline(pipeline.Get(),desc);Check(FloatDrawFlags()&1,"Native draw PSO was not cloned");Check(desc.InputLayout.pInputElementDescs[0].Format==DXGI_FORMAT_R16G16B16A16_UNORM,"Original PSO layout mutated");
 std::vector<FloatSkinVertex> vertices={{{1.1f,-.9f,0},{7,1,0,0},{128,121,0,0}},{{2.9f,-.9f,0},{7,1,0,0},{128,121,0,0}},{{2,.9f,0},{7,1,0,0},{128,121,0,0}}};
 auto delivery=std::make_shared<RenderDelivery>();delivery->epoch=1;delivery->sequence=1;delivery->resources.push_back({0,36547,0,46,435936,{1,1,1},{0,0,0}});delivery->floatVertices.resize(36547);for(unsigned i=0;i<3;i++){auto& to=delivery->floatVertices[i];to.position=vertices[i].position;to.normal=(128u<<20)|0x40000000;to.tangent=0xc0000000;std::memcpy(&to.bones,vertices[i].bones.data(),4);std::memcpy(&to.weights,vertices[i].weights.data(),4);}LiveRenderFeed(delivery);
 delivery->resources[0].lodFirstVertex[1]=10;delivery->resources[0].lodVertexCount[1]=3;for(unsigned i=0;i<3;i++)delivery->floatVertices[10+i]=delivery->floatVertices[i];
 auto reference=std::make_shared<std::vector<RenderDelivery::MorphReference>>(36547);for(auto& row:*reference){row.position={32767.f/65535,123.f/65535,43200.f/65535};row.normal=(128u<<20)|0x40000000;row.tangent=0xc0000000;}
 // The live native morph input deliberately differs from the cooked reference.
 // Native+delta must recover the intended triangle; replaying the cooked
 // absolute stream would place both bottom corners wholly outside the view.
 for(unsigned i=0;i<2;i++)for(unsigned axis=0;axis<3;axis++){(*reference)[i].position[axis]+=4;delivery->floatVertices[i].position[axis]+=4;}
 (*reference)[2].boundary=7;delivery->morphReference=reference;
 auto buffer=[&](UINT64 bytes,D3D12_HEAP_TYPE type,D3D12_RESOURCE_STATES state){D3D12_HEAP_PROPERTIES heap{};heap.Type=type;D3D12_RESOURCE_DESC r{};r.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;r.Width=bytes;r.Height=1;r.DepthOrArraySize=1;r.MipLevels=1;r.SampleDesc.Count=1;r.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;ComPtr<ID3D12Resource> out;HR(device->CreateCommittedResource(&heap,D3D12_HEAP_FLAG_NONE,&r,state,nullptr,IID_PPV_ARGS(&out)));return out;};
 auto uv=buffer(24,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);float uvData[]={.25f,0,.25f,0,.25f,0};void* mapped=nullptr;D3D12_RANGE none{0,0};HR(uv->Map(0,&none,&mapped));std::memcpy(mapped,uvData,24);uv->Unmap(0,nullptr);
 D3D12_HEAP_PROPERTIES defaultHeap{};defaultHeap.Type=D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC textureDesc{};textureDesc.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;textureDesc.Width=64;textureDesc.Height=64;textureDesc.DepthOrArraySize=1;textureDesc.MipLevels=1;textureDesc.Format=DXGI_FORMAT_R32G32B32A32_FLOAT;textureDesc.SampleDesc.Count=1;textureDesc.Flags=D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;
 ComPtr<ID3D12Resource> texture;HR(device->CreateCommittedResource(&defaultHeap,D3D12_HEAP_FLAG_NONE,&textureDesc,D3D12_RESOURCE_STATE_RENDER_TARGET,nullptr,IID_PPV_ARGS(&texture)));
 D3D12_DESCRIPTOR_HEAP_DESC heapDesc{};heapDesc.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;heapDesc.NumDescriptors=1;ComPtr<ID3D12DescriptorHeap> heap;HR(device->CreateDescriptorHeap(&heapDesc,IID_PPV_ARGS(&heap)));auto rtv=heap->GetCPUDescriptorHandleForHeapStart();device->CreateRenderTargetView(texture.Get(),nullptr,rtv);
 D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};UINT rows=0;UINT64 rowBytes=0,bytes=0;device->GetCopyableFootprints(&textureDesc,0,1,0,&footprint,&rows,&rowBytes,&bytes);auto readback=buffer(bytes,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST),morphReadback=buffer(bytes,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);
 ComPtr<ID3D12CommandAllocator> allocator;HR(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)));ComPtr<ID3D12GraphicsCommandList> list;HR(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),pipeline.Get(),IID_PPV_ARGS(&list)));
 list->SetGraphicsRootSignature(root.Get());D3D12_VIEWPORT viewport{0,0,64,64,0,1};D3D12_RECT rect{0,0,64,64};list->RSSetViewports(1,&viewport);list->RSSetScissorRects(1,&rect);list->OMSetRenderTargets(1,&rtv,FALSE,nullptr);float clear[4]{};list->ClearRenderTargetView(rtv,clear,0,nullptr);list->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
 auto packed=buffer(36547*24,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);HR(packed->Map(0,&none,&mapped));std::memset(mapped,0,36547*24);for(unsigned i=0;i<36547;i++){auto* row=static_cast<unsigned char*>(mapped)+i*24;const std::uint16_t words[]{32767,123,43200,65535};std::memcpy(row,words,8);const std::uint32_t tangent=0xc0000000;std::memcpy(row+20,&tangent,4);}packed->Unmap(0,nullptr);D3D12_VERTEX_BUFFER_VIEW views[]={{packed->GetGPUVirtualAddress(),36547*24,24},{uv->GetGPUVirtualAddress(),24,8},{packed->GetGPUVirtualAddress()+16,36547*24-16,24}};list->IASetVertexBuffers(0,3,views);unsigned restored=0;auto restore=[&]{++restored;list->SetComputeRootSignature(root.Get());list->SetPipelineState(pipeline.Get());};Check(FloatDraw(list.Get(),pipeline.Get(),views[0],views[2],[&]{list->DrawInstanced(3,1,0,0);},0,2,packed.Get(),D3D12_RESOURCE_STATE_GENERIC_READ,restore),"Native float draw was not applied");Check(FloatDraw(list.Get(),pipeline.Get(),views[0],views[2],[&]{list->DrawInstanced(3,1,0,0);},0,2,packed.Get(),D3D12_RESOURCE_STATE_GENERIC_READ,restore)&&restored==1,"Native morph was recomputed for every draw");
 D3D12_RESOURCE_BARRIER morphBarrier{};morphBarrier.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;morphBarrier.Transition={texture.Get(),D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE};list->ResourceBarrier(1,&morphBarrier);D3D12_TEXTURE_COPY_LOCATION morphDst{},morphSrc{};morphDst.pResource=morphReadback.Get();morphDst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;morphDst.PlacedFootprint=footprint;morphSrc.pResource=texture.Get();morphSrc.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;list->CopyTextureRegion(&morphDst,0,0,0,&morphSrc,nullptr);std::swap(morphBarrier.Transition.StateBefore,morphBarrier.Transition.StateAfter);list->ResourceBarrier(1,&morphBarrier);
 FloatDrawFrameBoundary();
 // A second engine list must consume the first list's native frame even if
 // the background surface publishes newer geometry between depth/material.
 auto changed=std::make_shared<RenderDelivery>(*delivery);changed->sequence=2;
 for(auto& row:changed->floatVertices)row.bones=0;changed->floatVertices[12].normal=123u|(450u<<10)|(789u<<20)|0x40000000u;changed->floatVertices[12].tangent=456u|(321u<<10)|(654u<<20)|0xc0000000u;LiveRenderFeed(changed);
 HR(list->Close());auto depthList=list;ComPtr<ID3D12CommandAllocator> materialAllocator;HR(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&materialAllocator)));list.Reset();HR(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,materialAllocator.Get(),pipeline.Get(),IID_PPV_ARGS(&list)));
 list->SetGraphicsRootSignature(root.Get());list->RSSetViewports(1,&viewport);list->RSSetScissorRects(1,&rect);list->OMSetRenderTargets(1,&rtv,FALSE,nullptr);list->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);list->IASetVertexBuffers(1,1,&views[1]);
 auto staticBuffer=buffer(256,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);D3D12_VERTEX_BUFFER_VIEW staticPosition{staticBuffer->GetGPUVirtualAddress(),256,16},staticLighting{staticBuffer->GetGPUVirtualAddress()+64,192,8};list->IASetVertexBuffers(0,1,&staticPosition);list->IASetVertexBuffers(2,1,&staticLighting);list->ClearRenderTargetView(rtv,clear,0,nullptr);Check(FloatDraw(list.Get(),pipeline.Get(),staticPosition,staticLighting,[&]{list->DrawInstanced(3,1,0,0);},0,1),"Static LOD slice was not applied");
 RenderResource staticContract;staticContract.lodVertexCount={5457,3391};staticContract.lodUVOffset={5457*16,174624+3391*16};Check(StaticFloatDrawLOD(staticContract,0)==0&&StaticFloatDrawLOD(staticContract,174624)==1&&StaticFloatDrawLOD(staticContract,16)==2,"Position-only static LOD identification differs from native stream offsets");
 Check(!FloatDraw(list.Get(),pipeline.Get(),staticPosition,staticLighting,[&]{throw std::runtime_error("Unknown static LOD reached GPU draw");},0,2),"Ambiguous static LOD was replaced with LOD0");
 D3D12_VERTEX_BUFFER_VIEW absentLighting{};list->IASetVertexBuffers(2,1,&absentLighting);list->ClearRenderTargetView(rtv,clear,0,nullptr);Check(FloatDraw(list.Get(),pipeline.Get(),staticPosition,absentLighting,[&]{list->DrawInstanced(3,1,0,0);},0,1),"Static position-only depth pass was not applied");
 D3D12_RESOURCE_BARRIER barrier{};barrier.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;barrier.Transition={texture.Get(),D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE};list->ResourceBarrier(1,&barrier);
 D3D12_TEXTURE_COPY_LOCATION dst{},src{};dst.pResource=readback.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint=footprint;src.pResource=texture.Get();src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);HR(list->Close());
 D3D12_COMMAND_QUEUE_DESC queueDesc{};ComPtr<ID3D12CommandQueue> queue;HR(device->CreateCommandQueue(&queueDesc,IID_PPV_ARGS(&queue)));ComPtr<ID3D12Fence> fence,other;HR(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)));HR(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&other)));
 ID3D12CommandList* lists[]={depthList.Get(),list.Get()};queue->ExecuteCommandLists(2,lists);FloatDrawSubmitted(queue.Get(),2,reinterpret_cast<void* const*>(lists));HR(queue->Signal(fence.Get(),1));HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);Check(event!=nullptr,"Fence event creation failed");HR(fence->SetEventOnCompletion(1,event));auto waited=WaitForSingleObject(event,10000);CloseHandle(event);Check(waited==WAIT_OBJECT_0,"GPU output timed out");
 Check((FloatDrawFlags()&256)&&!(FloatDrawFlags()&128)&&FloatDrawSequence()==1&&FloatDrawActive(1)&&!FloatDrawActive(2),"Native draw completion or epoch isolation failed");FloatDrawReset(list.Get());
 D3D12_RANGE read{0,static_cast<SIZE_T>(bytes)};HR(readback->Map(0,&read,&mapped));const auto pixel=reinterpret_cast<const float*>(static_cast<const unsigned char*>(mapped)+footprint.Offset+32*footprint.Footprint.RowPitch+32*16);std::array<float,4> color{};std::memcpy(color.data(),pixel,16);readback->Unmap(0,&none);
 Check(std::abs(color[0]-1)<1e-6f&&std::abs(color[1]-128.f/249.f)<1e-6f&&std::abs(color[2]-.25f)<1e-6f&&std::abs(color[3]-(1+128.f/1023))<1e-6f,"Unbounded position/skin/other-stream GPU draw differs");
 HR(morphReadback->Map(0,&read,&mapped));std::memcpy(color.data(),static_cast<const unsigned char*>(mapped)+footprint.Offset+32*footprint.Footprint.RowPitch+32*16,16);morphReadback->Unmap(0,&none);Check(std::abs(color[0]-1)<1e-6f&&std::abs(color[3]-1)<.125f,"Actual native morph baseline/lighting was replaced by cooked rest");
 FloatDrawFrameBoundary();
 // Read ONLY the final LOD vertex. A mixed triangle hid the AMD IA behavior:
 // a 28-byte view shortened by 20 bytes loses its final complete input record.
 // Two point instances return N and T separately, without interpolation.
 auto lastVS=Shader(R"(
struct Input{float3 n:NORMAL;float4 t:TANGENT;};struct Output{float4 p:SV_Position;float4 color:COLOR;};
Output main(Input v,uint instance:SV_InstanceID){Output o;o.p=float4((1.0+2.0*instance)/64.0,-1.0/64.0,0,1);o.color=instance?v.t:float4(v.n,1);return o;}
)","vs_5_0");auto lastDesc=desc;lastDesc.VS={lastVS->GetBufferPointer(),lastVS->GetBufferSize()};lastDesc.PrimitiveTopologyType=D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT;ComPtr<ID3D12PipelineState> lastPSO;HR(device->CreateGraphicsPipelineState(&lastDesc,IID_PPV_ARGS(&lastPSO)));RegisterFloatDrawPipeline(lastPSO.Get(),lastDesc);
 ComPtr<ID3D12CommandAllocator> lastAllocator;ComPtr<ID3D12GraphicsCommandList> lastList;HR(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&lastAllocator)));HR(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,lastAllocator.Get(),lastPSO.Get(),IID_PPV_ARGS(&lastList)));lastList->SetGraphicsRootSignature(root.Get());lastList->RSSetViewports(1,&viewport);lastList->RSSetScissorRects(1,&rect);lastList->OMSetRenderTargets(1,&rtv,FALSE,nullptr);lastList->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_POINTLIST);
 auto lastBarrier=barrier;std::swap(lastBarrier.Transition.StateBefore,lastBarrier.Transition.StateAfter);lastList->ResourceBarrier(1,&lastBarrier);lastList->ClearRenderTargetView(rtv,clear,0,nullptr);lastList->IASetVertexBuffers(0,1,&staticPosition);lastList->IASetVertexBuffers(2,1,&staticLighting);Check(FloatDraw(lastList.Get(),lastPSO.Get(),staticPosition,staticLighting,[&]{lastList->DrawInstanced(1,2,2,0);},0,1),"Last lighting vertex was not drawn");std::swap(lastBarrier.Transition.StateBefore,lastBarrier.Transition.StateAfter);lastList->ResourceBarrier(1,&lastBarrier);lastList->CopyTextureRegion(&dst,0,0,0,&src,nullptr);HR(lastList->Close());ID3D12CommandList* lastLists[]{lastList.Get()};queue->ExecuteCommandLists(1,lastLists);FloatDrawSubmitted(queue.Get(),1,reinterpret_cast<void* const*>(lastLists));ComPtr<ID3D12Fence> lastFence;HR(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&lastFence)));HR(queue->Signal(lastFence.Get(),1));event=CreateEventW(nullptr,FALSE,FALSE,nullptr);Check(event!=nullptr,"Last vertex fence event creation failed");HR(lastFence->SetEventOnCompletion(1,event));waited=WaitForSingleObject(event,10000);CloseHandle(event);Check(waited==WAIT_OBJECT_0,"Last lighting vertex GPU readback timed out");
 HR(readback->Map(0,&read,&mapped));std::array<float,8> lastValues{};std::memcpy(lastValues.data(),static_cast<const unsigned char*>(mapped)+footprint.Offset+32*footprint.Footprint.RowPitch+32*16,32);readback->Unmap(0,&none);const float expectedLast[]{123.f/1023,450.f/1023,789.f/1023,1,456.f/1023,321.f/1023,654.f/1023,1};for(unsigned i=0;i<8;i++)Check(std::abs(lastValues[i]-expectedLast[i])<1e-6f,"Last vertex normal/tangent record was truncated or corrupted");FloatDrawReset(lastList.Get());
 FloatDrawFrameBoundary();
 HR(materialAllocator->Reset());HR(list->Reset(materialAllocator.Get(),pipeline.Get()));list->SetGraphicsRootSignature(root.Get());list->RSSetViewports(1,&viewport);list->RSSetScissorRects(1,&rect);list->OMSetRenderTargets(1,&rtv,FALSE,nullptr);list->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);list->IASetVertexBuffers(1,1,&views[1]);
 std::swap(barrier.Transition.StateBefore,barrier.Transition.StateAfter);list->ResourceBarrier(1,&barrier);list->ClearRenderTargetView(rtv,clear,0,nullptr);
 list->IASetVertexBuffers(0,1,&staticPosition);list->IASetVertexBuffers(2,1,&absentLighting);Check(FloatDraw(list.Get(),pipeline.Get(),staticPosition,absentLighting,[&]{list->DrawInstanced(3,1,0,0);},0,1),"New SDK frame was not drawn");
 std::swap(barrier.Transition.StateBefore,barrier.Transition.StateAfter);list->ResourceBarrier(1,&barrier);list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);HR(list->Close());ID3D12CommandList* newer[]={list.Get()};queue->ExecuteCommandLists(1,newer);FloatDrawSubmitted(queue.Get(),1,reinterpret_cast<void* const*>(newer));HR(queue->Signal(fence.Get(),2));event=CreateEventW(nullptr,FALSE,FALSE,nullptr);Check(event!=nullptr,"Next-frame fence event creation failed");HR(fence->SetEventOnCompletion(2,event));waited=WaitForSingleObject(event,10000);CloseHandle(event);Check(waited==WAIT_OBJECT_0,"Next-frame GPU output timed out");
 HR(readback->Map(0,&read,&mapped));std::memcpy(color.data(),static_cast<const unsigned char*>(mapped)+footprint.Offset+32*footprint.Footprint.RowPitch+32*16,16);readback->Unmap(0,&none);Check(color[0]==0&&FloatDrawSequence()==2,"SDK-frame boundary froze old geometry");FloatDrawReset(list.Get());
 std::cout<<"PASS: actual FloatDraw backend clones original PSO, substitutes 28-byte surface input, preserves bone/weight/UV input, renders beyond UNORM range and selects static LOD slices from trailing-allocation views; separate depth/material command lists retain one SDK-frame publication, original bindings restored and fenced epoch/sequence completion reported; SDK output only\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
